apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: mysql-pvc
